//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWorkSqlOrnek
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURUN
    {
        public int ID { get; set; }
        public string AD { get; set; }
        public string MARKA { get; set; }
        public Nullable<int> FIYAT { get; set; }
        public Nullable<int> STOK { get; set; }
    }
}
